---
- name: Install GitBucket
  hosts: gitbucket
  sudo: yes
  vars_files:
    - ../vars/common.yml
  roles:
    - ../common-roles/base
    - ../common-roles/jetty
    - ../common-roles/apache
    - gitbucket
